[project]
name = "meeting-room-manager"
version = "0.1.0"
description = "Meeting Room Booking System for CAA - Computer Science NEA"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "flask-login>=0.6.3",
]
